SELECT trunc(l.DATAFOLHA , 'MONTH') COMPETENCIA , s.SETOR SETOR, s.DESCRICAO40 PROJETO, v.vdb, v.DESCRICAO30 VERBA , sum(l.HORASQUANTIDADE) HH
FROM RHMETA.RHCONTRATOS c
, RHMETA.rhvdb v
, RHMETA.rhsetores s
, RHMETA.RHVDBFOLHA l
WHERE l.VDB = v.VDB 
AND l.CONTRATO = c.CONTRATO 
AND c.SETOR = s.SETOR
-- AND trunc(l.DATAFOLHA , 'MONTH') >= trunc(CURRENT_DATE, 'MONTH')
AND trunc(l.DATAFOLHA , 'MONTH') = trunc(CURRENT_DATE, 'MONTH') + INTERVAL '-1' MONTH
AND v.VDB IN (1, 69470, 69100, 69110, 69050, 69055, 69060, 69070, 69070, 69090, 50001, 50101)
GROUP BY trunc(l.DATAFOLHA , 'MONTH'), s.SETOR ,s.DESCRICAO40 , v.vdb, v.DESCRICAO30
ORDER BY trunc(l.DATAFOLHA , 'MONTH'), s.SETOR , s.DESCRICAO40, v.vdb
